In [19]:
import pandas as pd

df = pd.read_csv("globalAirQuality.csv")
#basic functions of dataframe that help to deal with files complex data
df.head()
df.tail()
df.sample()
df.info()
df.describe()
df.nunique()
df.columns
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    18000 non-null  object
 1   country      18000 non-null  object
 2   city         18000 non-null  object
 3   latitude     18000 non-null  float64
 4   longitude    18000 non-null  float64
 5   pm25         18000 non-null  float64
 6   pm10         18000 non-null  float64
 7   no2          18000 non-null  float64
 8   so2          18000 non-null  float64
 9   o3           18000 non-null  float64
 10  co           18000 non-null  float64
 11  aqi          18000 non-null  int64
 12  temperature  18000 non-null  float64
 13  humidity     18000 non-null  float64
 14  wind_speed   18000 non-null  float64
dtypes: float64(11), int64(1), object(3)
memory usage: 2.1+ MB

(18000, 15)

In [45]:
df.loc[0:2]
df.iloc[0:2]
df.loc[0,["aqi","city"]]
df.loc[0:2,["city","aqi"]]
#for same work with iloc 
df.iloc[0:2,[1,2]]#pass columns index
df.at[0,"city"]
df.iat[0,2]

'New York'

In [81]:
#filter the data with square brackets[]
df[df["city"]=="New York"]
df[(df["aqi"]>180) & (df["city"] == "Paris")]

df[df["aqi"]<50 ]["city"]

22          New York
43          New York
252         New York
533      Los Angeles
807           London
            ...
17624       Helsinki
17713         Zurich
17811         Zurich
17962         Zurich
17986         Zurich
Name: city, Length: 158, dtype: object

In [93]:
# with query()

df.query("aqi < 30")
city_name = "New York"
df.query("city == @city_name")[["aqi","country"]]

#use single codes to compare string
df.query("city == 'Paris'")

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
1080,2025-11-04 18:25:17.554219,FR,Paris,48.857,2.352,32.613,57.886,38.008,7.401,58.504,0.812,95,27.674,81.397,3.808
1081,2025-11-04 19:25:17.554219,FR,Paris,48.857,2.352,76.137,107.376,13.843,8.838,49.477,0.948,152,16.097,78.543,6.050
1082,2025-11-04 20:25:17.554219,FR,Paris,48.857,2.352,58.671,59.403,21.702,4.706,24.174,0.920,117,14.632,60.744,4.729
1083,2025-11-04 21:25:17.554219,FR,Paris,48.857,2.352,33.720,125.245,36.352,2.801,36.053,0.942,125,10.215,73.734,3.659
1084,2025-11-04 22:25:17.554219,FR,Paris,48.857,2.352,38.569,69.995,28.946,6.079,47.118,0.585,77,25.785,75.848,7.062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1435,2025-11-19 13:25:17.554219,FR,Paris,48.857,2.352,38.255,32.191,46.281,2.736,18.458,0.689,115,36.599,35.471,8.345
1436,2025-11-19 14:25:17.554219,FR,Paris,48.857,2.352,46.705,96.561,43.951,5.410,51.630,0.766,109,32.841,73.376,2.396
1437,2025-11-19 15:25:17.554219,FR,Paris,48.857,2.352,56.741,83.278,30.401,10.778,21.667,0.617,113,35.328,86.456,1.573
1438,2025-11-19 16:25:17.554219,FR,Paris,48.857,2.352,35.457,52.212,38.549,4.602,46.749,0.963,96,31.677,25.206,3.653
1439,2025-11-19 17:25:17.554219,FR,Paris,48.857,2.352,34.836,51.383,19.369,5.041,19.478,0.054,69,16.651,39.894,1.311

In [84]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403